### ISSUE TITLE
용어 사전 어떻게 사용하나요?

### ISSUE THREAD

**Issue by kasdfi9sdf8** [hve4638/ai-front#1]
위키를 봐도 잘 모르겠습니다

용어사전 기능은 어떻게 사용하나요?

**Comment by hve4638** [comment]
용어 사전은 프로그램 내에서 프롬프트에 사용자가 추가로 입력할 수 있는 기능으로 이해하고 설명하겠습니다.

간단하게 설명하면, list.json의 변수 목록에 type이 `text` 또는 `text-multiline`인 변수를 추가하고 프롬프트 파일에 `{{변수명}}`을 추가하면 됩니다.

```js
{
    "prompts": [
        {
            "name": "테스트",
            "key": "testprompt",
            "value": "testprompt",
			"vars" : [
				{
					"name" : "instruction",
					"display_name" : "지시사항",
					"type" : "text-multiline"
				}
			]
        }
    ]
}
```

*prompts* 폴더에 위치하는 `list.json` 예제입니다. `vars` 필드 내의 요소는 변수명은 "*instruction*", 사용자에게 표시되는 이름은 "*지시사항*"이며 사용자가 프론트엔드에서 원하는 값을 추가할 수 있는 타입의 변수를 추가하는 것을 의미합니다.

```md
## Instruction

{{instruction}}

## User Input

{{:input}}
```

*prompts* 폴더에 위치하는 `testprompt` 프롬프트 템플릿 예제입니다. 위의 `list.json`에서 프롬프트 정보의 `value`가 "*testprompt*"이므로 파일명은 동일하게 "*testprompt*"로 작성해야 합니다.

`{{}}` 중괄호 문법을 통해 "*instruction*" 변수를 넣습니다. 프롬프트 템플릿 내의 `{{instruction}}`은 전송시 사용자가 입력한 변수값으로 변환되게 됩니다.
