### ISSUE TITLE
Gemini API 사용시 오류

### ISSUE THREAD

**Issue by snake7594** [hve4638/ai-front#3]
Exception Occur!

Error: undefined (undefined)

어제까지 잘 되던게, 오늘 아침부터 에러가 발생합니다. 뭐가 문제일까요?
다시 해보니 ChatGPT도 동일한 오류가 나네요.
저만 발생하는 오류인지 싶어서 질문 드립니다.

**Comment by hve4638** [comment]
정확한 모델명과 사용한 프롬프트, 입력한 텍스트를 올려주세요.

텍스트가 개인적이거나, 프롬프트에 탈옥 문구 등이 포함되어있는 등의 Issue에 직접적으로 올리기 어렵다면 hve4638@gmail.com 으로 보내주시면 됩니다.

**Comment by snake7594** [comment]
빠른 피드백 감사합니다!
문제는 해결했습니다.
간단히 말씀드리면, gemini api 설정의 문제였습니다.
SSL 부분에서 계속 오류가 났었고,
그래서 'Exception Occur! Error: undefined (undefined)'라는 메시지가 반복적으로 나왔던 것 같습니다.
구글 클라우드 API 설정 부분에서 사용자 인증 정보를 수정하니 정상 동작됩니다.
이건 제가 사용하는 네트워크나 기타 보안 프로그램의 영향일 수도 있습니다.
또, Open api에서 나는 오류는 이유는 모르겠으나, 일시적이었던 것 같습니다. 지금은 정상 동작합니다.

지금 번역에 본 프로그램을 사용하고 있는데 아주 만족스럽습니다.
한가지 제안을 드리면,
지금도 충분히 잘 쓰고 있지만, 긴 텍스트의 번역이나 파일을 번역하는 등의 향상이 이뤄지면 참 좋겠다는 생각입니다!

감사합니다!

**Comment by snake7594** [comment]
제가 간단한 파이썬 코드로 동작을 확인해 봤습니다.

`import google.generativeai as genai

import os

genai.configure(api_key='your_key')
model = genai.GenerativeModel("gemini-1.5-pro")

response = model.generate_content("한국의 겨울 날씨는 어떻습니까?")
print(response.text)`

이렇게 코드를 실행하면,


`python g.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1731055102.569945   23392 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055102.679137    4328 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055102.774360   23300 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055102.913976    3960 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055103.006778    5844 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055103.104807   16108 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055103.205543    3964 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055103.317857    6780 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055103.456455   15584 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
E0000 00:00:1731055103.601346   16108 ssl_transport_security.cc:1654] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
한국의 겨울 날씨는 지역에 따라 차이가 있지만, 전반적으로 춥고 건조합니다. 일반적으로 12월부터 2월까지가 겨울이며, 가장  추운 시기는 1월입니다.

* **기온:**  평균 기온은 영하로 내려가며, 특히 중부 내륙 지방의 경우 영하 10도 이하로 떨어지는 경우도 잦습니다.  서울의 1월 평균 기온은 약 -3°C에서 -6°C 정도입니다. 남부 지방은 상대적으로 온화하며, 제주도는 영상의 기온을 유지하는 경우가 많 습니다.

* **강수량:** 겨울철 강수량은 다른 계절에 비해 적습니다. 눈은 주로 12월 말부터 2월까지 내리며, 특히 서해안 지역에 많은  눈이 내리는 경향이 있습니다.  동해안 지역은 겨울철에 건조한 북서풍의 영향을 받아 눈이 적게 내립니다.

* **바람:** 겨울에는 북서풍이 강하게 불어 체감 온도를 더 낮춥니다. 특히 산악 지대에서는 바람이 매우 강하게 불 수 있습니 다.

* **지역별 특징:**
    * **서울/경기/강원:** 춥고 건조하며, 눈이 자주 내립니다.  강원도 산간 지역은 매우 춥고 눈이 많이 옵니다.
    * **충청/전라:** 중부 지방보다는 온화하지만, 역시 겨울에는 춥습니다. 서해안 지역은 눈이 많이 내립니다.
    * **경상/부산:** 남부 지방으로 비교적 온화한 겨울을 보냅니다. 눈은 많이 내리지 않습니다.
    * **제주:** 아열대 기후의 영향으로 한국에서 가장 따뜻한 겨울을 보냅니다. 눈보다는 비가 더 자주 내립니다.


요약하자면, 한국의 겨울은 춥고 건조하며, 지역에 따라 기온과 강설량의 차이가 큽니다.  따라서 겨울 여행을 계획한다면, 방문 지역의 날씨 정보를 미리 확인하고 적절한 옷차림을 준비하는 것이 중요합니다.`


이렇게 몇번 오류 내다가 결국 답을 줍니다. 혹시 오류를 무시하고 처리되는게 가능할까요?

**Comment by hve4638** [comment]
AIFront와 위의 python 코드를 반복적으로 실행해보았지만 문제를 재현할 수 없었습니다. 네트워크 문제나 인증서 문제일 가능성이 높아 도움을 주기 어려울 것 같습니다. 오류 발생 시 재요청 옵션은 이후 추가하도록 하겠습니다.

긴 텍스트 처리에 대해서는 추후 일정 길이의 입력에 대해 요청을 나누어 보내는 프롬프트 설정을 추가해 개선할 예정입니다. 이미지 및 텍스트 파일에 대해서도 추후 추가할 예정입니다.

**Comment by snake7594** [comment]
답변 감사합니다! 
아직은 해결은 안됐지만, 타 네트워크와 PC에서는 잘 동작하는 걸로 봐서는, 제가 봐도 제 PC 환경의 문제로 보입니다.
너무나 유용하게 활용하고 있어서 이 자리를 빌어 다시 한번 감사드립니다!
