### ISSUE TITLE
제미니 exp 지원해주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by kasdfi9sdf8** [hve4638/ai-front#4]
제미니 EXP가 무료사용이라고 합니다. 지원해주시면 감사하겠습니다.

그리고 얼마후에 2도 나온다고 하네요.

**Comment by hve4638** [comment]
Gemini 1.5 Pro-002, Gemini 1.5 Pro Exp 0827 모델을 지원 목록으로 추가하였습니다
