### ISSUE TITLE
Batch API 제안

### ISSUE THREAD

**Issue by kasdfi9sdf8** [hve4638/ai-front#5]
Batch API (https://platform.openai.com/docs/guides/batch) 라는게 있더군요.

작업물을 일단 보내놓으면 시간될때 처리해서 보내주는 대신 가격이 싼 기능인것 같습니다.

이 기능을 번역기에 사용하면 좋을것 같은데 혹시 시간나시거나 관심있으시면 한번 보시면 괜찮을것 같습니다.

언제나 번역기 정말 잘 쓰고 있습니다. 감사드려요.

**Comment by hve4638** [comment]
네, 추후 추가하도록 하겠습니다
